spring:
  datasource:
    url: jdbc:postgresql://db:5432/ecommerce
    username: ecommerce_user
    password: ecommerce_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
